-- CreateTable
CREATE TABLE "Organization" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "plan" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Organization_pkey" PRIMARY KEY ("id")
);

-- Seed default organization for existing data backfill.
INSERT INTO "Organization" ("id", "name")
VALUES (1, 'Default Organization')
ON CONFLICT ("id") DO NOTHING;

SELECT setval(
  pg_get_serial_sequence('"Organization"', 'id'),
  GREATEST((SELECT COALESCE(MAX("id"), 1) FROM "Organization"), 1),
  true
);

-- AlterTable
ALTER TABLE "User" ADD COLUMN "organizationId" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Technician" ADD COLUMN "organizationId" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Customer" ADD COLUMN "organizationId" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Intervention" ADD COLUMN "organizationId" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Site" ADD COLUMN "organizationId" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Job" ADD COLUMN "organizationId" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "WorkReport" ADD COLUMN "organizationId" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Media" ADD COLUMN "organizationId" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "PushSubscription" ADD COLUMN "organizationId" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "InterventionAttachment" ADD COLUMN "organizationId" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "WorkReportAttachment" ADD COLUMN "organizationId" INTEGER NOT NULL DEFAULT 1;

-- CreateIndex
CREATE INDEX "User_organizationId_idx" ON "User"("organizationId");
CREATE INDEX "Technician_organizationId_idx" ON "Technician"("organizationId");
CREATE INDEX "Customer_organizationId_idx" ON "Customer"("organizationId");
CREATE INDEX "Intervention_organizationId_idx" ON "Intervention"("organizationId");
CREATE INDEX "Site_organizationId_idx" ON "Site"("organizationId");
CREATE INDEX "Job_organizationId_idx" ON "Job"("organizationId");
CREATE INDEX "WorkReport_organizationId_idx" ON "WorkReport"("organizationId");
CREATE INDEX "Media_organizationId_idx" ON "Media"("organizationId");
CREATE INDEX "PushSubscription_organizationId_idx" ON "PushSubscription"("organizationId");
CREATE INDEX "InterventionAttachment_organizationId_idx" ON "InterventionAttachment"("organizationId");
CREATE INDEX "WorkReportAttachment_organizationId_idx" ON "WorkReportAttachment"("organizationId");

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Technician" ADD CONSTRAINT "Technician_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Customer" ADD CONSTRAINT "Customer_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Intervention" ADD CONSTRAINT "Intervention_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Site" ADD CONSTRAINT "Site_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Job" ADD CONSTRAINT "Job_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "WorkReport" ADD CONSTRAINT "WorkReport_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Media" ADD CONSTRAINT "Media_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PushSubscription" ADD CONSTRAINT "PushSubscription_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InterventionAttachment" ADD CONSTRAINT "InterventionAttachment_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "WorkReportAttachment" ADD CONSTRAINT "WorkReportAttachment_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
